model_params:
  name: "CategoricalVAE"
  categorical_dim: 4
  action_dim: 14
  context_dim: 3
  hidden_dims: [50,50]
  temperature: 0.5
  anneal_rate: 0.00003
  anneal_interval: 100
  alpha: 1.0

data_params:
  data_path: "/Users/jsi/Documents/neural-robotic-arm-master/src/data/libfranka_joints/processed/A_B"
  train_batch_size: 256
  val_batch_size: 256
  test_batch_size: 256
  num_workers: 4

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.001
  manual_seed: 1265

trainer_params:
  accelerator: "gpu"
  # devices: [0,1,2]
  max_epochs: 200

logging_params:
  save_dir: "/home3/jacobyhsi/neural-robotic-arm-master/logs"
  name: "cat-vae-PNP-ee-Jacob"
